services:
  db_postgres:
    container_name: postgres2
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: gestao_viagem_turismo
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d

  pgadmin2:
    container_name: pgadmin2
    image: dpage/pgadmin4
    ports:
      - "8080:80" # Acesso ao pgAdmin via navegador (porta 8080)
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com # E-mail de login do pgAdmin
      PGADMIN_DEFAULT_PASSWORD: admin # Senha de login do pgAdmin
    volumes:
      - pgadmin_data:/var/lib/pgadmin # Volume persistente para configurações do pgAdmin

volumes:
  postgres_data:
  pgadmin_data:
